# SPDX-FileCopyrightText: 2022 Magenta ApS
# SPDX-License-Identifier: MPL-2.0

stages:
  - build
  - release

variables:
  RELEASE_REGISTRY_IMAGE: index.docker.io/magentaaps/postgres-keycloak-init
  IMAGE_SHA: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}

include:
  - project: labs/salt-automation
    file: gitlab-ci-templates/common/docker-build-meta.v1.yml
  - project: labs/salt-automation
    file: gitlab-ci-templates/common/docker-release.v1.yml

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID

build:
  extends: .build-docker
  variables:
    DOCKERFILE: ${CI_PROJECT_DIR}/docker/Dockerfile
